### PR TITLE
log when atomic file move not possible

### PR DESCRIPTION
**Pull request by aledsage**
See discussion in https://github.com/apache/incubator-brooklyn/pull/891, @alexmuntean 

Also fixes compilation error in o.a.b.util.time.Time, introduced in commit a340dbc311c19aef84c6b98d4d91b7776932212a

### CODE REVIEW

**Comment by aledsage** [comment]
Very minor; merging now (and it fixes compilation error in master).

**Comment by aledsage** [comment]
@alexmuntean @ahgittin any post-merge comments, then do let me know.
